import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import styles from '../styles/Home.module.css'
import {  gql } from "@apollo/client";
import client from "../apollo-client";

const Feed_query = gql`{
  feed {
    id
    title
  }
}`

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
    query {
      feed {
        id
        title
        img
        url
      }
    }
    `,
  });

  return {
    props: {
      comics: data.feed,
    },
 };
}

export default function Home({comics}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Marvel Universe Reading Order</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      
          {comics.map((link) => (
            <>
            <p key={link.id}>{link.title}</p>
            <Link href={link.url}>
              <a>
                <Image src={link.img} width={225} height={139} alt={link.title} />
             </a>
             </Link>
            </>
            
          ))}
        
      </div>

      
    </div>
  )
}
