import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import styles from '../styles/Home.module.css'
import { Text, Box, Stack, extendTheme } from '@chakra-ui/react';

const theme = extendTheme({
  textStyles: {
    h1: {
      textShadow: '-1px 1px 2px #000, 1px 1px 2px #000, 1px -1px 0 #000, -1px -1px 0 #000,'
    }
  }
})


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Marvel Universe Reading Order</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      
         
          <Box mt='85px' mr='85px'>
            <Link href='/about'>
              <a>
              <Image src={'/pics/about@3x.png'} width='209px' height='100px'/>
              </a>
            </Link>
          </Box>
          

          <Stack>
          <Box>
            <Text textShadow={'-12px 0px black'} color='#d25050' fontFamily={'OstrichSans'} fontSize='180px' fontWeight={'900'}>
              MARVEL EARTH 616
            </Text>
          </Box>
          <Box align='right' pb='40px' pr='90px'>
            <Link href="/avenger_dissamble">
              <a>
              <Image src={'/pics/avengers-disassemble@3x.png'} width='823px' height='100px'/>
              </a>
            </Link>
          </Box>

          <Box align='right' pb='40px' pr='90px'>
            <Link href="/house_of_m">
              <a>
              <Image src={'/pics/house-of-m@3x.png'} width='338px' height='100px'/>
            </a>
            </Link>
          </Box>
          
          <Box align='right' pb='40px' pr='90px'>
            <Link href="/civil_war">
            <a>
            <Image src={'/pics/civil-war@3x.png'} width='381px' height='100px'/>
            </a>
            </Link>
            </Box>
          </Stack>
        
      </div>      
    </div>
  )
}
